### ISSUE TITLE
How to check if json property is null 

### ISSUE THREAD

**Issue by vaz83** [bblanchon/ArduinoJson#1049]
Hello,
what's the best way to check if a json property exists or has value ? i was trying to make the condition jDoc["relayInterval"]!=NULL but it's not working.
`
        File configFile = SPIFFS.open("/configsa.json", "r");
        size_t size = configFile.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);
        configFile.readBytes(buf.get(), size);
        DynamicJsonDocument jDoc(2500);
        DeserializationError error = deserializeJson(jDoc,buf.get());
        if (!error)
        {
           if(jDoc["relayInterval"]!=NULL)
              strcpy(relay_interval,jDoc["relayInterval"]);
        }
'

**Comment by bblanchon** [comment]
Hi @vaz83,

You cannot use `NULL` because ArduinoJson confuses it with 0, the integer ([see explanation](https://cpp4arduino.com/2018/10/26/why-cpp-programmers-dont-use-null.html))

Instead, you can use `nullptr` or [JsonObject::containsKey()](https://arduinojson.org/v6/api/jsonobject/containskey/).

Best Regards,
Benoit
