### ISSUE TITLE
Can't create an int64_t field in StaticJsonDocument

### ISSUE THREAD

**Issue by pabloVecchio** [bblanchon/ArduinoJson#1104]
Hi, i'm trying to implement your library (v6), but i can't figure out how to create a int64_t field. In this function:

bool Class::Function ( int64_t value, String text )  {
	StaticJsonDocument<500> doc;
	doc["value"] = value;
	doc["text"] = text;
	String msg;
	serializeJson(doc, msg);
	return workWith(msg);
}

doc["value"] is always cast to 32 bits, even defining: 
#define ARDUINOJSON_USE_LONG_LONG 1
#include "ArduinoJson.h"     // there is no other include for ArduinoJson.h

There is a way to create a json with a int64_t field ?

Thanks!

**Comment by bblanchon** [comment]
Hi @pabloVecchio,

Which platform are you targetting?

Best Regards,
Benoit

**Comment by pabloVecchio** [comment]
Sorry, i didn't say that, it's a ESP8266. I can read the int_64 value doing:
int64_t var = doc["key"]; // ie: "key": 68719476735 //(0xFFFFFFFFF)
But not write

**Comment by bblanchon** [comment]
The library works fine on PC, as you can see on this demo:
https://wandbox.org/permlink/ksXpcoDQL0n3BXeo

So there might be something wrong with ESP8266.
Let me try to reproduce the issue...

**Comment by bblanchon** [comment]
Hi @pabloVecchio,

I just tried on an ESP8266, and it works like a charm when [ARDUINOJSON_USE_LONG_LONG](https://arduinojson.org/v6/api/config/use_long_long/) is set to 1.

I guess that you have several compilation units (several `.cpp`/`.ino`), but only defined ARDUINOJSON_USE_LONG_LONG for one of them. You must use the same value in each compilation unit; otherwise, your program will embed two variants of the library: one with `long long` and one without.

Best Regards,
Benoit

**Comment by pabloVecchio** [comment]
You're right!! I forgot that i have a ' #include "ArduinoJson.h" ' in another file, added ARDUINOJSON_USE_LONG_LONG there too and is working!
Thanks a lot for your time!!

**Comment by bblanchon** [comment]
You're welcome @pabloVecchio.
Good luck with your project.
And don't forget to [star the project](https://github.com/bblanchon/ArduinoJson/stargazers) to show your support 😉
