### ISSUE TITLE
DeseralizeJSON returns invalid input on equals strings

### ISSUE THREAD

**Issue by meetinger** [bblanchon/ArduinoJson#1148]
Hello, I need to read a JSON from SD card, but this lib returns errors, then I decided to copy the output from the serial port and paste it directly into the code, but even then the library gives an error ... 
Maybe something in charset, but the characters are exactly the same ..

(code in file)

UPD: it's a charset incompatibility

[testor.txt](https://github.com/bblanchon/ArduinoJson/files/3972482/testor.txt)

**Comment by mkfrey** [comment]
You have a unicode character ([byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) 0xEFBBBF) right before this backslash:
```
String test = "﻿{\"test\":\"10\"}"; //error
----------------^ here
```

**Comment by bblanchon** [comment]
Thanks @codefrey.

@Yanchik0402, here is your find viewed with [HxD](https://mh-nexus.de/en/hxd/):

![image](https://user-images.githubusercontent.com/5462433/71323115-f37b5d80-24cf-11ea-82ba-b8ae9be98ef1.png)

**Comment by meetinger** [comment]
In what charset I need to create files on SD so that there is no incompatibility?

**Comment by mkfrey** [comment]
ASCII or UTF-8 would be your best bets, as long as you are not using exotic characters.

However, the encoding is not the problem with your file. The problem is that you have a character in the JSON which is not enclosed in quotation marks.

If we replaced the character causing the trouble (which is interpreted as a zero-width non-breaking space, so it's basically invisible) with an 'x', your JSON string would look like `String test = "﻿{x\"test\":\"10\"}";`, which does not represent a valid JSON. Just remove this hidden character and you should be good to go.
