### ISSUE TITLE
[Question] Append std::vector by pointer/reference (Without copy or iterating the object) to JsonArray object.

### ISSUE THREAD

**Issue by judalvarezca** [bblanchon/ArduinoJson#1196]
Did I read de FAQ? yes.
Problem: I have a `std::vector<double>` buffer on one of my objects. It stores data from a sensor, and I want to get all the buffer and post it to a frontend with REST methods. Is there an easy way to append the complete object to the JsonArray, without a for? my current piece of code:

```
JsonArray array = doc->createNestedArray("data");
//Maybe something like this?
double* a = &taskParametersc1.buffer[0];
array.add(a);
```

By the look on [https://arduinojson.org/v6/api/jsonarray/add/](url) I would say no, but maybe you can put me on the right track about the Library tools. Meanwhile I'll look into docs to find a clue.

Thank you!

**Comment by judalvarezca** [comment]
By the way, currently I've figured a solution, in the form:
```
for (auto j = params->buffer.begin(); j != params->buffer.end(); ++j) {
    array.add(*j);
}
```
And my question is just curiosity about the pointer/reference capabilities of the tool.

**Comment by bblanchon** [comment]
Hi @judalvarezca,

There is the utility function [copyArray()](https://arduinojson.org/v6/api/misc/copyarray/), but it doesn't natively support `std::vector`, so you need to pass a pointer and a size:

```c++
copyArray(v.data(), v.size(), array);
```

See a demo here: https://wandbox.org/permlink/ouoV9XHCSTuccEMK

I'm marking this as a feature request because [copyArray()](https://arduinojson.org/v6/api/misc/copyarray/) should support `vector` natively.

Best regards,
Benoit

**Comment by bblanchon** [comment]
PS:
I read the title of this issue again.
No, we cannot do that without making a copy. 
I understand it would be a nice optimization, but I don't currently plan on implementing that.

**Comment by judalvarezca** [comment]
Oh, I see, yeah I understand, it probably will be a lot of work. Thank you for your advice :)

Regards.
