### ISSUE TITLE
DynamicJsonDocument capacity allocation fails even through enough memory.

### ISSUE THREAD

**Issue by c-klinger** [bblanchon/ArduinoJson#1257]
Hi, 
i try to serialize a bigger dataset and have the issue that my code works randomly. I figured out, that it seems the allocation of the DynamicJsonDocument fails. I don't understand the reason for that, as Heap looks fine for all cases:
```
Serial.println(ESP.getFreeHeap());
DynamicJsonDocument doc(4096);
Serial.println(doc.capacity());
```

Example Output:
```
5640
0

6672
4096

6376
0
```
Any ideas? Or i'm just underestimating the "buffer" of heap that has to be free after allocation of DynamicJsonDocument?

Platform: ESP8266 (ESP-12E / NodeMCU)

**Comment by bblanchon** [comment]
Hi @c-klinger,

You cannot allocate a block of 4096 bytes even if there are a total a 5640 bytes available because the heap is fragmented.

To get the largest available block, you must use `ESP.getMaxFreeBlockSize()`.

See also:

* [What is heap fragmentation?](https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html)
* [BasicJsonDocument<T>::shrinkToFit()](https://arduinojson.org/v6/api/basicjsondocument/shrinktofit/)

Best regards,
Benoit
