### ISSUE TITLE
Global DynamicJsonDocument 

### ISSUE THREAD

**Issue by Avenitos** [bblanchon/ArduinoJson#1270]
Hello! I need a global DynamicJsonDocument object. But I don't want the memory to be allocated immediately at the moment of creation. It is necessary either at the time of first use or on command. Can I do this? Thanks!

**Comment by bblanchon** [comment]
Hi @Avenitos,

No, it's not possible.

Also, I strongly discourage your form using a global JsonDocument, because it would create [a memory leak](https://arduinojson.org/v6/faq/i-found-a-memory-leak-in-the-library/).
ArduinoJson is a serialization library, not a generic container.

Best regards,
Benoit
