### ISSUE TITLE
Dynamic String to Json Parameter

### ISSUE THREAD

**Issue by ramenia** [bblanchon/ArduinoJson#1277]
Hi,

I am trying to add a string parameter to json and publish it with mqtt but when i publish this json :
```
String stationID = "abc";
jsonString["Station ID"] = stationID;
```
I get this json from mqtt
`Station ID : null`
but if i publish this:
```
jsonString["Station ID"] = "abc";
```
Everthing is OK. What am i doing wrong ?

```
StaticJsonDocument<2048> jsonString;

    jsonString["Station ID"] = (stationID);   
    jsonString["Station Type"] = (stationType);
    jsonString["Station Use Count"] = (stationUseCount);

    String output;
    serializeJson(jsonString, output);
    output.toCharArray(jsonArray, output.length() + 1);
    serializeJson(jsonString, wifiClient);
    client.publish("iotDeneme", jsonArray);
```

**Comment by bblanchon** [comment]
Hi,

ArduinoJson didn't find enough room to copy the string, so it replaced it with `null`.

See:

* [The serialized document contains `null` instead of a string](https://arduinojson.org/v6/error/document-contains-null-instead-of-string/)
* [How to use ArduinoJson with PubSubClient?](https://arduinojson.org/v6/how-to/use-arduinojson-with-pubsubclient/)

Also, 2KB is pretty large for a [`StaticJsonDocument`](https://arduinojson.org/v6/api/staticjsondocument/); consider switching to a [`DynamicJsonDocument`](https://arduinojson.org/v6/api/dynamicjsondocument/).

Best regards,
Benoit
