### ISSUE TITLE
The elements in the JsonArray getting replaced when I use JsonArray::add().

### ISSUE THREAD

**Issue by Bharath-M-R** [bblanchon/ArduinoJson#1306]
Hi,
For the first time ,when data received its getting stored into the jsonArray properly.But if the next time data comes,I expect the data to be added at the end of the current jsonArray,But what happening is that the newly came data replaces the first came and getting added at the last also.

This is that part of code:

StaticJsonBuffer <2048>jsonBuffer1;
StaticJsonBuffer <2048>jsonBuffer2;

JsonObject& wifilist = jsonBuffer2.createObject();
JsonArray& mac_list = wifilist.createNestedArray("MAC");

void loop()
{
  while(Serial.available())
  {
    String payload = Serial.readString();
    JsonObject& parsed = jsonBuffer1.parseObject(payload);

     for(int i=0;i< parsed_contain_array_length ; i++)
     {
         mac_list.add(parsed["MAC"][i]);
     }

Any solutions...?

Thanks,
Bharath

**Comment by bblanchon** [comment]
Hi Bharath,

These `StaticJsonBuffer`s are huge!
What platform are you using?

Also, this program is very curious; can you explain the logic?

Note that ArduinoJson 5, stores `JsonObject` by reference.
When you do `mac_list.add(parsed["MAC"][i])`, you add a pointer from `jsonBuffer2` to `jsonBuffer1`.
So if you modify the object in one document, it will appear as changed in the other because it's the same instance.
This is different from ArduinoJson 6, which copies the object.

Best regards,
Benoit

**Comment by Bharath-M-R** [comment]
Hi,
I am using Arduino IDE.
I will explain the situation.
I have two modules, every one minute the first module sends the json data to the second module through serial connection.
In the second module I need to receive, parse it and store it into another jsonArray and whenever data receives I want to add these data into the JsonArray . the JsonArray keep on getting added by the data sent by first module.
I hope u understand my explanation.
thanks

**Comment by Bharath-M-R** [comment]
Hi bblanchon,
 Thanks for your response..  :)
My issue resolved by using only one jsonBuffer instead of the two. Thank you.
