### ISSUE TITLE
msgpack serialization not implemented yet?

### ISSUE THREAD

**Issue by hyansuper** [bblanchon/ArduinoJson#1378]
I love its friendly interface.
but serialization of msgpack is not found in example, do you have plan to support serialization?

**Comment by bblanchon** [comment]
Hi @hyansuper,

MessagePack serialization is supported since [ArduinoJson 6.0.0](https://arduinojson.org/news/2018/06/07/version-6-0-0/).
I didn't add a dedicated example because it would be extremely similar to [JsonGeneratorExample.ino](https://arduinojson.org/v6/example/generator/).
Indeed, you simply need to replace [`serializeJson()`](https://arduinojson.org/v6/api/json/serializejson/) with [`serializeMsgPack()`](https://arduinojson.org/v6/api/msgpack/serializemsgpack/).

Best Regards,
Benoit
