### ISSUE TITLE
use filter to get all elements of an array

### ISSUE THREAD

**Issue by MartinNohr** [bblanchon/ArduinoJson#1408]
In your example for filtering:
StaticJsonDocument<64> filter;
filter["list"][0]["temperature"] = true;
This works fine if you only want part of an array, but what if you wanted all of the elements in the array?
I tried
StaticJsonDocument<64> filter;
filter["list"] = true;
but it only returns the first member of the array. I want all of them.
This is obviously silly for your example, but I have a case where the array is down one level and I need all of the members of the array. I made it work by listing all of the array elements, but that results in lots of lines in the filter.
I would like to capture all of the array items from "daily" in the openweather call "onecall".
I've attached a sample json.
[openweatheronecall.txt](https://github.com/bblanchon/ArduinoJson/files/5378882/openweatheronecall.txt)

**Comment by bblanchon** [comment]
Hi @MartinNohr,

`filter["daily"] = true` should include the complete array.

If you only see the first element, it's probably because there was not enough room in the [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/).
Did you check the result of [deserializeJson()](https://arduinojson.org/v6/api/json/deserializejson/)?

Best regards,
Benoit
