### ISSUE TITLE
Filter with ID

### ISSUE THREAD

**Issue by CN20222** [bblanchon/ArduinoJson#1721]
Hi how can i filter with Assistant this

`[
 {
   "id": 1,
   "ingredients": [
      {
         "id": 5,
         "amount": 108
      },
      {
         "id": 8,
         "amount": 12
      }
   ]
},
 {
   "id": 2,
   "ingredients": [
      {
         "id": 4,
         "amount": 12
      },
      {
         "id": 6,
         "amount": 108
      }
   ]
},
 {
   "id": 3,
   "ingredients": [
      {
         "id": 4,
         "amount": 24
      },
      {
         "id": 6,
         "amount": 96
      }
   ]
},
 {
   "id": 4,
   "ingredients": [
      {
         "id": 4,
         "amount": 12
      },
      {
         "id": 5,
         "amount": 108
      }
   ]
},
 {
   "id": 5,
   "ingredients": [
      {
         "id": 4,
         "amount": 24
      },
      {
         "id": 5,
         "amount": 96
      }
   ]
}
]`

for example only ID 2

`
[ 
{
   "id": 2,
   "ingredients": [
      {
         "id": 4,
         "amount": 12
      },
      {
         "id": 6,
         "amount": 108
      }
   ]
}
]
`
Thanks for your help

**Comment by bblanchon** [comment]
Hi @CN20222,

Unfortunately, the filtering feature introduced in [ArduinoJson 6.15](https://arduinojson.org/news/2020/03/22/version-6-15-0/) only allows including/excluding members based on the key, not the value. Admittedly, this is pretty limited but it's sufficient for many use cases and has a minimal impact on code size.

Filtering by value has been requested several times (https://github.com/bblanchon/ArduinoJson/issues/1486#issuecomment-778051459, https://github.com/bblanchon/ArduinoJson/issues/1316, https://github.com/bblanchon/ArduinoJson/issues/1708) but has not been implemented because it's much more complicated than it seems.  
Indeed, there are tricky use cases to cover; for example, you could exclude all "users" objects whose age is "< 18" (and that's an easy one).
If you go down this road, you soon realize that you need the equivalent of a `WHERE` clause in SQL.

This could be implemented with a callback in the filter document, but this is incompatible with the design constraints for ArduinoJson 6, which forbids `virtual` functions.
Another solution would be to support [JSONPath](https://goessner.net/articles/JsonPath/), but the language is complex, so the implementation would require a lot of work and would be quite big.

With the current implementation, your options are:

1. to deserialize the entire document and loop through each member to find the right one (https://github.com/bblanchon/ArduinoJson/issues/1708#issuecomment-1032548837)
2. to deserialize each object one by one and ignore the ones that don't match (see [Deserialization in chunks](https://arduinojson.org/v6/how-to/deserialize-a-very-large-document/#deserialization-in-chunks)).

Hopefully, one of these workarounds suits you.

Best regards,
Benoit
