### ISSUE TITLE
Send serialize object in http response without using String buffer

### ISSUE THREAD

**Issue by chess-levin** [bblanchon/ArduinoJson#1736]
I'm using ESP2866WebServer and ArduinoJson (both most recent versions) to implement a REST-API. I'm trying to get rid of all String usages in my code, because I have trouble with heap fragmentation. I'm wondering whats the best way to omit this `String buf;`
but can't find an example in your excellent documentation of the ArduinoJson library. May you could help with a small piece of demo code?

And asked more generally what's the best way to deal with memory fragmentation problems when using ArduinoJson. I've already read your excellent article on this topic (https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html). 

My REST-API is frequently (every 5s) called from one Client/Browser. There are no parallel clients accessing the wemos d1 mini. The size of the Json Document is 768Byte. You explicitly advice against using a global JsonDocument, but wouldn't this be the solution around heap fragmentation?

```
void handleGetSateJson() {
  PRINTSLN("handleGetSateJson()");
  DynamicJsonDocument doc(stateJsonDocSize);
  serializeSysInfo(doc);
  String buf;
  serializeJson(doc, buf);
  httpServer.send(200, F("application/json"), buf);
}
```

**Comment by bblanchon** [comment]
Hi,

As you learned in [What is heap fragmentation](https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html), allocations of constant size don't increase fragmentation.
As you can see in [8 tips to use the String class efficiently](https://cpp4arduino.com/2018/11/21/eight-tips-to-use-the-string-class-efficiently.html), you can call `String::reserve()` to allocate the buffer.

So, here is the way you can use `serializeJson()` and `String` without increasing the fragmentation:

```c++
String buf();
buf.reserse(2048); // choose a value that this sufficiently large for all valid use cases
serializeJson(doc, buf);
```

Don't worry about the memory consumption overhead, it's only for a fraction of a second.
It's much better to allocate more memory than to fragment the heap.

Of course, you could avoid the `String` class and allocate your buffer with `malloc()`, `new[]`, or `make_unique`, but I think using `String` in this case it simpler.

However, you cannot replace the `String` with a `char[2048]` because it would overflow the stack. (If this sentence doesn't make sense, please read the second chapter of [my book](https://arduinojson.org/book/)).

Best regards,
Benoit
