### ISSUE TITLE
Is binary blob allowed with msgpack?

### ISSUE THREAD

**Issue by hyansuper** [bblanchon/ArduinoJson#1765]
I know json does not allow binary. but I am using msgpack, can I serialize/deserialze a blob of binary data using msgpack?
Supporse I want to transfer a picture, but when the binary data contains 0, The output is truncated. 
```
#include <ArduinoJson.h>

void setup() {
  Serial.begin(115200);    
  uint8_t raw[]={0,101,102,103,104,105,106,107,108,109};
  StaticJsonDocument<512> doc;  
  doc["fmt"]="jpeg";
  doc["data"] = raw;
  Serial.println("serialize:");
  serializeMsgPack(doc, Serial);
  // output: ⸮⸮fmt⸮jpeg⸮data⸮
}

void loop() {
}
```
Or should I use [JsonArray](https://arduinojson.org/v6/api/jsonarray/)? can I initiate it with raw data, something like `JsonArray a; a->buf=raw` ?

**Comment by bblanchon** [comment]
Hi @hyansuper,

ArduinoJson does not yet support MessagePack binary values (see #922).

However, with the current version, you can send strings that contain NUL characters.
To do so, you must use a string type that supports NUL (like `std::string`, `std::string_view`, or [`JsonString`](https://arduinojson.org/v6/api/jsonstring/), but not `const char*`).
For example, you can write this:

```c++
doc["data"] = JsonString((const char*)raw, sizeof(raw));
```

The cast to `const char*` isn't mandatory but avoids duplication.
Indeed, ArduinoJson treats `const char*` differently to avoid duplicating string literals.
This rule applies to all strings you insert in a `JsonDocument`, including `JsonString`.

I expect to add binary support for MessagePack in 6.21, but I don't want to make any commitment.
According to the traffic on arduinojson.org, MessagePack is used by about 5.5% of ArduinoJson users; that's why I don't put the highest priority on this feature, but I will implement it eventually.

Best regards,
Benoit

**Comment by hyansuper** [comment]
thank you! I use msg pack because I need a RPC that supports binary data streaming as well as other data types. 
using ArduinoJson is really handy, and the non-duplication feature makes it efficient

**Comment by hyansuper** [comment]
Oh, some related questions:
1. `doc["data"] = JsonString((const char*)raw, sizeof(raw));` sends binary blob as string, but the receiving device does not use ArduinoJson, will it be interpreted as string when deserialize? will additional NUL characters be inserted into the raw data?
2. I don't know how raw data and strings are translated into msgpack format respectivly (I guess raw data is sent as is with some additional overhead, but strings are compressed/coded), if I treat raw data as strings in the method above, will it be conpressed? cause the compression process may slow down transfer speed, considering efficiency.

**Comment by bblanchon** [comment]
1. Make sure the receiver doesn't try to decode UTF-8 characters.
2. There is no translation, nor compression in the MessagePack format.
