### ISSUE TITLE
jsonBuffer size and parseObject() failed

### ISSUE THREAD

**Issue by roccomuso** [bblanchon/ArduinoJson#177]
Hi,

Why this code gives me a parseObject() failed error on Serial Monitor, what am I doing wrong?
My json string is very short. According to the documentation, JSON_OBJECT_SIZE is supposed to be 1 in my case or not?

    String mex = "{\"cmd\": \"self_advertise\"}";

    const int BUFFER_SIZE = JSON_OBJECT_SIZE(1);
    StaticJsonBuffer<BUFFER_SIZE> jsonBuffer;
    
    JsonObject& root = jsonBuffer.parseObject(mex);

     if (!root.success()){
        Serial.println("ArduinoJson parseObject() failed");
     }

**Comment by bblanchon** [comment]
Hi,

This is because `parseObject()` needs to modify the string.
Since you provide a `String`, which cannot be modified, it has to make a copy.

To fix this, either:

1. Increase the size of the `StaticJsonBuffer` by the number of characters in the string, or
2. replace the `String` by a `char[]`

Please read [FAQ: Why parsing fails?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#why-parsing-fails)

**Comment by roccomuso** [comment]
Thank you. Fixed using char[].

**Comment by bblanchon** [comment]
Yes, that's the most efficient choice.
Programmers coming from C# or Java usually want to use the `String` class, but most of the time it's a mistake.
