### ISSUE TITLE
Auto Checksum over Serial

### ISSUE THREAD

**Issue by adelin-mcbsoft** [bblanchon/ArduinoJson#1824]
Hi,

Is there an easy way to extend the library to validate (or hash-check) a JSON transferred over Serial (or any other stream-medium) ?
Are there already any built implementations or planned ones?

To do it manually means more overhead, as it requires custom computation of the checksum at the end of the JSON encoded message (when sending), and also parsing the new computed string (_JSON_ + _Checksum_) when deserializing, so it won't be possible anymore to use _single liners_ to transfer the data (e.g. `serializeJson(data, UART);` and `DeserializationError err = deserializeJson(data, UART);`) like we do for now.

Any input is greatly appreciated.
Thank you!

**Comment by bblanchon** [comment]
Hi @adelin-mcbsoft,

There is currently no single-line solution that appends the checksum to a JSON document, and I don't think there will ever be one.

However, you could build something similar by assembling existing blocks.
For example, you could either:

1. Compute the checksum with [CrcWriter](https://arduinojson.org/v6/how-to/compute-hash/). This would require calling `serializeJson()` twice (once with `Serial`, another time with `CrcWriter`), but the overhead is probably acceptable.
2. Modify [CrcWriter](https://arduinojson.org/v6/how-to/compute-hash/) so that it computes the checksum *and* sends to `Serial`. You'll probably want to create a custom reader to do the reverse operation on the receiver side.
3. Decorate `Serial` with a [`LoggingPrint`](https://github.com/bblanchon/ArduinoStreamUtils#logging-write-operations) that sends the log to a [`HashPrint`](https://arduinojson.org/v5/doc/tricks/#compute-hash-of-json-output). On the receiver, you must replace `LoggingPrint` with `ReadLogginStream`.

In any case, remember that `deserializeJson()` stops reading at the end of the document or at the first error, so the next byte in the stream might not be the checksum. In other words, if `deserializeJson()` returns an error, you must flush the remaining content, and if it returns `Ok`, the checksum might follow, but you can't be sure (e.g., stream contains a spurious `]` or `}`).

Alternatively, consider using the [HammingStream](https://github.com/bblanchon/ArduinoStreamUtils#how-to-use-error-correction-codes-ecc), but this class is relatively new and probably needs some refinements.

Best regards,
Benoit
