### ISSUE TITLE
.as<std::string>() returns literal "null" string  when property not present

### ISSUE THREAD

**Issue by Bascy** [bblanchon/ArduinoJson#1872]
**Describe the bug**  
When using below code when property "name" is not present in the Json document, the variable is set to the literal string "null":

```
  std::string variable = json["property"].as<std::string>();
```

**Workaround**
```
   std::string variable = json["property"] | "";
```

**Troubleshooter report**  
Here is the report generated by the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/):  
1. The issue happens at run time
2. The issue concerns deserialization
3. `deserializeJson()` returns `Ok`
4. Some strings are truncated
5. The input doesn't contain `\u0000`
6. The input doesn't come from an HTTP response

**Environment**  
Here is the environment that I used:
* Microcontroller: ESP32
* Core/runtime: Espressif 32 (5.3.0)
* IDE: VSCode

**Comment by bblanchon** [comment]
Hi @Bascy,

This is the expected behavior: when the value is not a string `as<std::string>()` returns the JSON representation.
However, this behavior was not documented, so I added [a section in the documentation](https://arduinojson.org/v6/api/jsonvariant/as/#asstring-and-asstdstring).

Best regards,
Benoit
