### ISSUE TITLE
allocate memory on SDRAM

### ISSUE THREAD

**Issue by yari0757** [bblanchon/ArduinoJson#2016]
"Hi, I am new to embedded development and C programming. I want to create a JSON document with three arrays, each with a size of 3000. However, my global variable memory size is not enough. Is there any way to define it on SDRAM? 
My board is an Arduino H7."

**Comment by bblanchon** [comment]
Hi @yari0757,

I don't own a Portenta H7, so I cannot test, but according to what I've read, you should be able to define a custom allocator that uses the SDRAM library.

Here is a sample code for ArduinoJson 6:

```c++
#include <SDRAM.h>
#include <ArduinoJson.h>

struct SdRamAllocator {
  void* allocate(size_t size) {
    return SDRAM.malloc(size);
  }

  void deallocate(void* ptr) {
    SDRAM.free(ptr);
  }
};

using SdRamJsonDocument = BasicJsonDocument<SdRamAllocator>;

SdRamJsonDocument doc(1024);
```

Note that this won't work with ArduinoJson 7, because it requires the allocator class to also support `realloc()`, which is not available on the SDRAM library (arduino/ArduinoCore-mbed#810).
Unfortunately, we cannot emulate `realloc()` because we don't have the size of the original block.

Best regards,
Benoit
