### ISSUE TITLE
Compile errors in Visual Micro / Visual Studio (Solved)

### ISSUE THREAD

**Issue by Dave1001** [bblanchon/ArduinoJson#238]
Hello bblanchon!

Letting you know of errors compiling in Visual Micro and Visual Studio 2015 (I switched from the regular Arduino IDE to Visual Micro about a year ago as it's much easier to debug)

Due to the non-standard library structure, ArduinoJson won't compile for older versions of Visual Micro - the solution is simply to upgrade to Visual Micro from January 2016 or later.

There's more information here on the cause of the [issue with the library structure] (http://www.visualmicro.com/forums/YaBB.pl?num=1454614540/0) and [deep library search] (http://www.visualmicro.com/post/2016/01/14/How-to-improve-compile-times-dramatically.aspx)

Great work on the library / many thanks

Dave

**Comment by bblanchon** [comment]
Hi Dave,

Thanks for the info!
I added it to the [Wiki: Compatibility Issues](https://github.com/bblanchon/ArduinoJson/wiki/Compatibility-issues#visual-micro--visual-studio).

Unfortunately, this kind of problem is very common since the introduction of the new library layout in Arduino 1.5.
That's one of the reason I'll make ArduinoJson 6 a header-only library (issue #199).

Regards,
Benoit
