### ISSUE TITLE
Strange float serialization

### ISSUE THREAD

**Issue by anisimovsergey** [bblanchon/ArduinoJson#506]
I looked at FAQ and Pitfalls and couldn't find the answer. Please take a look at the following tests, I find it rather strange that **OneFloatDefaultDigits3** passes successfully, does it exhibit expected behavior? 

```c++
  SECTION("OneFloatDefaultDigits2") {
    array.add(0.01f);
    check(array, "[0.01]");
  }

  SECTION("OneFloatDefaultDigits3") {
    array.add(0.001f);
    check(array, "[0.00]");
  }

  SECTION("OneFloatDefaultDigits4") {
    array.add(0.0001f);
    check(array, "[10.00e-5]");
  }
```

_I'm using Microsoft Visual Studio Enterprise 2015 Version 14.0.25123.00 Update 2_

**Comment by bblanchon** [comment]
Hello Sergey,

Yes this is the expected behavior.
It's been inherited from the Arduino's `Print` class.

However, this is going to change in the next few days as I completely rewrote the float serialization.
This will be available in v5.10.0, but you can checkout branch [issue427](https://github.com/bblanchon/ArduinoJson/tree/issue427) for a preview.

Regards,
Benoit

**Comment by anisimovsergey** [comment]
Hello Benoit,

Thank you for your prompt response. 

I'm not an expert in Arduiono but I find it's quite surprising that in the case of printing **0.001** I'm getting **0.00** but in case of other values like 0.01 and 0.0001 I'm getting some values (in the scientific notation or fixed point, doesn't matter much). 

I'll defensively check the preview. 

Cheers,
Sergey

**Comment by anisimovsergey** [comment]
Tested it on [issue427](https://github.com/bblanchon/ArduinoJson/tree/issue427) branch - working as expected. Looking forward to seeing it in a release.
