### ISSUE TITLE
Not compiling in Atmel Studio

### ISSUE THREAD

**Issue by esarearthur** [bblanchon/ArduinoJson#510]
Tried importing into atmel studio to use, but generated a lot of errors. Can this be used in atmel studio?
It works well with the arduino ide, but will like to use in atmel studio to allow me debug my code.
BR

**Comment by bblanchon** [comment]
Hello Ronald,

Yes, this can be used in Atmel Studio.

Can you copy/paste the compiler output in a [gist](https://gist.github.com/)?

Regards,
Benoit

**Comment by esarearthur** [comment]
[Error Generated link](https://gist.github.com/esarearthur/ae8cb63998729bc962ab61d0f70e287c)

This is blank project with only the header inserted and wont compile.

**Comment by bblanchon** [comment]
These errors are in the test suite.
I don't know how Atmel Studio works, but I bet there is a way to ignore `test/` and `fuzzing/`.

**Comment by esarearthur** [comment]
[Updated Error](https://gist.github.com/esarearthur/ae8cb63998729bc962ab61d0f70e287c)

I removed the test and fuzzy from the project but now it wont compile because of missing sstream used by catch

**Comment by bblanchon** [comment]
Sorry Ronald, I forgot `third-party/`

However, I think you should go the "single header" way.
Instead of cloning ArduinoJson and adding the library in AtmelStudio, you just download [ArduinoJson-v5.10.0.h](https://github.com/bblanchon/ArduinoJson/releases/download/v5.10.0/ArduinoJson-v5.10.0.h) and put it in your project folder.
This is a bullet-proof technique that works with all IDEs.

**Comment by bblanchon** [comment]
@esarearthur Any progress?

**Comment by bblanchon** [comment]
Added [a dedicated section in the FAQ](https://bblanchon.github.io/ArduinoJson/faq/atmel-studio/)
