### ISSUE TITLE
JsonVariant.createAnything hangs when in an interrupt.  

### ISSUE THREAD

**Issue by jamesthomasdavidson** [bblanchon/ArduinoJson#676]
```
StaticJsonBuffer<512> buf;
JsonObject& entry = buf.createObject();
JsonArray& acceleration_data = entry.createNestedArray("acceleration"); <- hangs right here. 
```
If i change this to be in a function _call_ as opposed to an _interrupt_, then it works beautifully.  

likewise, if buffer is a pointer to class member _buffer_, and this interrupt now lies in a class method
```
JsonObject& entry = buffer->createObject();
```
then this will hang the interrupt.

Any ideas?

James

**Comment by bblanchon** [comment]
Hi James,

It looks like a stack overflow.
`StaticJsonBuffer<512>` adds 512+ bytes in the stack.
Since that happens in an interrupt, it's added on top of the stack of the current thread.

Please see: https://en.wikipedia.org/wiki/Interrupt_handler

> In a low-level microcontroller, the chip might lack protection modes and have no memory management unit (MMU). In these chips, the execution context of an interrupt handler will be essentially the same as the interrupted program, which typically runs on a small stack of fixed size (memory resources have traditionally been extremely scant at the low end). Nested interrupts are often provided, which exacerbates stack usage. A primary constraint on the interrupt handler in this programming endeavour is to not exceed the available stack in the worst-case condition, requiring the programmer to reason globally about the stack space requirement of every implemented interrupt handler and application task.

I suggest that you use a `DynamicJsonBuffer`, or better: **don't do serialization in an interrupt handler**.
As a general rule, you should only perform rapid tasks in interrupts.

Regards,
Benoit
