### ISSUE TITLE
Possible JSON Parser memory inefficiency?

### ISSUE THREAD

**Issue by dragon-engineer** [bblanchon/ArduinoJson#718]
Hello,

I've been using the ArduinoJson library for some time with no issues (Great job, thank you!). I use it on **ESP8266** with DynamicBuffer, and it all works with no crashes.
Just now I did some memory optimizations in my complex code and I noticed quite a strange behavior (as for memory management):

Let's say I use the parser:
`globalVar = root["a"]["b"].as<uint32_t>(); // This consumes 20 bytes at most (still quite a bit tho)
globalVar = root["helloWorld_very_long_item_name"]["my_data_longname_longdata"].as<uint32_t>();`

With the second line the code is consuming up to 200 bytes of extra RAM.

My question is: is this normal? Or am I missing something? It seems a little bit strange that these are const char* arrays and they consume so much memory. With many global variables parsed it is significant amount of memory.
Note that the code builds and works in all ways, I am just trying to get some extra memory.
The fact that something is apparently copied over and consumes RAM only when accessing keys in Json Objects seems very inefficient.

Thank you for possible explanation, I hope I am missing something

**Comment by bblanchon** [comment]
Hello @matasondrak,

An object is a collection of key-value pair.
The bigger the key, the bigger the object.

As I explain in "The Missing C++ Course" of [Mastering ArduinoJson](https://arduinojson.org/book/?utm_source=github&utm_medium=issues), string literals are stored in the "global" area of the RAM.
You can reduce the RAM usage by moving these strings to Flash memory, like this:

```c++
globalVar = root[F("helloWorld_very_long_item_name")][F("my_data_longname_longdata")].as<uint32_t>();
```

ArduinoJson will pull the string from the Flash memory to the RAM at the moment of execution, which is better than keeping the string in the RAM all the time.
Of course, the program will be slower, so make sure you measure the impact.
Also, there is one caveat: don't repeatedly insert Flash strings in an object, because ArduinoJson will make several copies of it and you'll end up using more RAM than with a classic string literal.

So, this is what I can say about string literals, but I think there is a more fundamental issue in your program. The name `gloablVar` suggests that the variable is global. I strongly recommended not to use global variables for many reasons. In this case, the reason is that you freeze a large amount of RAM for the whole execution of the program; and that RAM cannot be used for other purposes. It's better to use a local variable that only uses RAM for a short time.

See also:

* [FAQ: Why shouldn't I use a global JsonBuffer?](https://arduinojson.org/faq/why-shouldnt-i-use-a-global-jsonbuffer/?utm_source=github&utm_medium=issues)

Regards,
Benoit

**Comment by matasondrak** [comment]
Thank you for reply.  I read all through the FAQ and your tutorials, tips and the assistant.
I already tried using the string literal with the F yesterday. However it still consumes RAM, I guess this is just normal. (At first I expected no memory consumption at all but apparently I was wrong).
There might be a misunderstanding on the globals: I use local DynamicBuffer and global variables such as my own structs for sensors data, time, configuration etc. that really need to be global.

**Comment by bblanchon** [comment]
Hi @matasondrak,

Even if you use Flash strings, ArduinoJson copies them into the RAM as soon as you use them in an object.
BTW, how do you measure RAM usage ?

**Comment by matasondrak** [comment]
Just the build output, simple as that..

Program mySketch size: 469 277 bytes (used 45% of a 1 044 464 byte maximum) (4,11 secs)
Minimum Memory Usage: 44432 bytes (54% of a 81920 byte maximum)

is there any other way?

**Comment by bblanchon** [comment]
The first line is the executable size in Flash memory. Every string that you add to the program makes this number go up.

The second line shows the size of global variables. Flash strings don't affect this number.
Unfortunately, this gives no clue of the RAM consumption at runtime, which is the most important to you.

They are various tricks to get the runtime RAM consumption, they depend on the platform.
For instance, if you use an ESP8266, you can call `ESP.getFreeHeap()`.

**Comment by bblanchon** [comment]
Sorry about that.
I didn't realize I was stating the obvious.
Hopefully, it will be helpful for other users.
