### ISSUE TITLE
Understanding use after free example from book

### ISSUE THREAD

**Issue by dpetican** [bblanchon/ArduinoJson#730]
I don't grok this example from the book about use after free:

```
// Create an empty JSON object
JsonObject& obj = jb.createObject();
// Set the name of the pin
obj["pin"] = (String("D") + pinId).c_str();
// The temporary String is destructed after the semicolon (;)
// Use-after-free
obj.printTo(Serial)
```
Doesn't the value of the expression on the right hand side of the equal sign get assigned to to obj["pin"] before the semicolon (so-to-speak) and then when the String is destructed after the semicolon it shouldn't matter?  Obviously something else is going on, but what? Thanks.

**Comment by bblanchon** [comment]
(for the record, @dpetican is referring to the Troubleshooting chapter of [Mastering ArduinoJson](https://arduinojson.org/book/?utm_source=github&utm_medium=issues))

Yes, it gets assigned before the destruction of the `String`, but in this particular situation, ArduinoJson saves the pointer, not a copy of the string.
Let's reveal the temporary variables to make it apparent.

The lines

```c++
obj["pin"] = (String("D") + pinId).c_str();
obj.printTo(Serial);
```

are virtually equivalent to

```c++
{
  String tmp1 = String("D") + pin1; // create temp String
  const char* tmp2 = tmp1.c_str(); // get a pointer to the chars in tmp1
  obj["pin"] = tmp2 ; // save the pointer
}
obj.printTo(Serial); // Ooops! tmp1 has be destroyed
```

Remember that the policy of ArduinoJson is to copy `char*` and `String`, and to save pointers to `const char*`. This policy avoids copying the string literals because there don't move.

I hope it's clear now; please tell me if it's not.

Also, thanks for buying the book :-)

**Comment by dpetican** [comment]
Thanks its very obvious now ;)  I think the missing C++ course and the troubleshooting chapter are worth the money by itself.  Very useful for C programming dinosaurs like myself.
