### ISSUE TITLE
arduinojson decode

### ISSUE THREAD

**Issue by Arash-HR** [bblanchon/ArduinoJson#737]
How to convert json to this format :
`{\"ip\":\"192.168.1.1\",\"macaddress\":\"ab:3c:5r:95}`

**Comment by RayyanTahir** [comment]
Hi, I haven't been able to use much of ArduinoJson library and my answer may be wrong, but I think the actual JSON format is like: `{"ip":"192.168.1.1","macaddress":"ab:3c:5r:95"}`

The probably reason you have believed in the format you mentioned in your question is because your console prints or shows the json string that way. the `\` character is generally used to escape the `"` character. Which means that `\"` simply translates to `"`. I hope that answers your confusion.

**Comment by Arash-HR** [comment]
@RayyanTahir To use the arduino library, I must have a character entry, so I must change the json template to use this library. Anyway, thank you so much

**Comment by Arash-HR** [comment]
Duplicate of #737
To use the arduino library, I must have a character entry, so I must change the json template to use this library. Anyway, thank you so much

**Comment by Arash-HR** [comment]
To use the arduino library, I must have a character entry, so I must change the json template to use this library. Anyway, thank you so much .
