### ISSUE TITLE
When (not) to use flash strings

### ISSUE THREAD

**Issue by dpetican** [bblanchon/ArduinoJson#738]
This references section 4.6 Duplication of strings in the book.

I can't quite figure out when/not to use flash strings to my best advantage.  Can you look at this section of code and tell me whats right/wrong.  Thanks.

```
if (request[F("cmd")] == "nvramset" && request.containsKey(F("start")) && request.containsKey(F("end"))
    && request.containsKey(F("values")) && request.containsKey(F("clientid"))) {
  StaticJsonBuffer<1024> respBuffer;
  JsonObject& response = respBuffer.createObject();
  response[F("cmd")] = F("nvramsetresp");
  response[F("clientid")] = request[F("clientid")];

  JsonArray& requestValues = request[F("values")];
  int requestValuesSize = requestValues.size();
  int start = request[F("start")], end = request[F("end")];

```

**Comment by bblanchon** [comment]
Hi @dpetican,

Let's take the example of the following line:

```c++
response[F("cmd")] = F("nvramsetresp");
```

ArduinoJson makes a copy of `"cmd"` and `"nvramsetresp"` in the `JsonBuffer`.
It would not need to do so if the strings were in RAM instead of Flash.
Two drawback: the program is significantly slower and required a bigger `JsonBuffer`.

Now, it's not a big deal in this program because it's not in a loop.
Real problems appear when a program creates an array of objects from Flash strings, because multiple copies of the strings are made in the `JsonBuffer` (ArduinoJson is not smart enough to make only one copy).

Also, you might wonder if the Flash strings are worth the extra complexity.
For example, in the code snippet above, the twelve `F()` macros are only saving 48 bytes of RAM, but they significantly reduce the speed of the program.
I don't think it's worth it.
So to answer you question: I would not use Flash string in this case.

A good use for Flash string are error messages, because they have very low impact on the overall performance and use a lot of memory.
As a comparison, this single `F()` macro saves 51 bytes:

```c++
Serial.println(F("An error occured, please contact customer support!"));
```

Regards,
Benoit
