### ISSUE TITLE
Parsing Multiple Object from sd Card

### ISSUE THREAD

**Issue by elpoba87** [bblanchon/ArduinoJson#838]
Hi,
I work to a datalogger Arduino based and i use the v5 of the ArduinoJson library. I have a necessity to read json object stored in a sd card **one by one**, extract values of the variables, store it and finally send through gsm module. I studied the example contents in your guide release extras(Readfromsdcard.ino), but i cant understand how i can change the script to adapt that example to my case (one array of  nested object to multiple simple object).

This is a example of my sd file:
{"timestamp":123456789,"temperature":32.4,"rain":4.5,"status":"ok"}{"timestamp":789964521,"temperature":21.2,"rain":3.8,"status":"out"}{"timestamp":254879563,"temperature":18.4,"rain":2.1,"status":"ok"}

Best Regards

**Comment by bblanchon** [comment]
Hi @elpoba87,

If the file contains a JSON array, like the following, you simply need to call [parseArray()](https://arduinojson.org/v5/api/jsonbuffer/parsearray/?utm_source=github&utm_medium=issues) instead of [parseObject()](https://arduinojson.org/v5/api/jsonbuffer/parseobject/?utm_source=github&utm_medium=issues).

```json
[{"timestamp":123456789,"temperature":32.4,"rain":4.5,"status":"ok"},{"timestamp":789964521,"temperature":21.2,"rain":3.8,"status":"out"},{"timestamp":254879563,"temperature":18.4,"rain":2.1,"status":"ok"}]
```

However, if it's a sequence of JSON object on different lines, you must keep [parseObject()](https://arduinojson.org/v5/api/jsonbuffer/parseobject/?utm_source=github&utm_medium=issues) but call it repeatedly.

We often use this technique to parse a big JSON document that cannot fit in memory.
See [Can I parse a JSON input that is too big to fit in memory?](https://arduinojson.org/v5/faq/can-i-parse-a-json-input-that-is-too-big-to-fit-in-memory/?utm_source=github&utm_medium=issues).

Regards,
Benoit
