### ISSUE TITLE
Arduino hangs upon clearing DynamicJsonBuffer

### ISSUE THREAD

**Issue by fortunate-man** [bblanchon/ArduinoJson#851]
I'm using a DynamicJsonBuffer to load data from a json file.

It seems to work perfectly, but when I try to clear the DynamicJsonBuffer, the arduino simply hangs. If I do not try to clear it, the function never seems to end, i.e, the next statement after the function call is never reached; however, a simple print on the last line of the function seems to be called.

Do note that the json file consists of character strings, and I'm using `strdup` to copy these `const char *` strings to an array of structures. I'm quite sure it is not a memory issue. 

I'm using an Arduino Mega 2560 R3.

**Comment by bblanchon** [comment]
Hi @fortunate-man,

You have to be very careful with [JsonBuffer::clear()](https://arduinojson.org/v5/api/jsonbuffer/clear/?utm_source=github&utm_medium=issues) because it invalidates all previously created objects. So, you need to make sure you don't keep a reference to a `JsonObject`, a `JsonArray` or a string.

I'm assuming you use `::strdup()` and not [JsonBuffer::strdup()](https://arduinojson.org/v5/api/jsonbuffer/strdup/?utm_source=github&utm_medium=issue), but are you sure that it doesn't return null? Because that would explain the undefined behavior.

BTW, the Arduino mega has only 8KB of RAM, if I were you I would not use the heap at all.

Can you share the code of the function (20 lines max please)?
Does it freeze immediately after `clear()`, or does it execute a few more lines?
(You can use [ArduinoTrace](https://github.com/bblanchon/ArduinoTrace) to verify)

Regards,
Benoit
