### ISSUE TITLE
getting length of an element and printTo an element

### ISSUE THREAD

**Issue by mars000** [bblanchon/ArduinoJson#898]
Quick question that I could not see an answer to in the docs.
if I have a json object; root and I have an element root["street_name"] = "Main"

is there a function in Arduino Json that:
1. returns the length of the content of  root["street_name"] i.e. length of "name" which would return length = 4

2. I know this won't complile : Serial.println(root["street_name"]);  is there a simple way I can acheive this without having to copying it into a String first ?

**Comment by bblanchon** [comment]
Hi @mars000,

To get the length of the string in `root["street_name"]`, simply call [`strlen()`](http://www.cplusplus.com/reference/cstring/strlen/):

```c++
int len = strlen(root["street_name"])
```

The result is 4 as you expect.

If you want to know the size of `root["street_name"]` in the JSON document, you can call [`measureLength()`](https://arduinojson.org/v5/api/jsonvariant/measurelength/?utm_source=github&utm_medium=issues):

```c++
int len = root["street_name"].measureLength();
```

The result is 6, because it counts the two quotes.

You cannot call `Serial.println()` with a `JsonVariant` because the compiler doesn't know which overload to call: is it the one for `int`, for `float`, or for `const char*`?
To solve this ambiguity, you have to explicitly extract the string pointer using [`JsonVariant::as<T>()`](https://arduinojson.org/v5/api/jsonvariant/as/?utm_source=github&utm_medium=issues):

```c++
Serial.println(root["street_name"].as<char*>());
```

Please see [this online demo](https://wandbox.org/permlink/V17rUbq6iYsSdEyZ).

Regards,
Benoit

**Comment by mars000** [comment]
Thanks for very clear and concise response.

**Comment by bblanchon** [comment]
You're welcome @mars000.
Thank you for using ArduinoJson.
Don't forget to star the project if you like it ;-)

**Comment by mars000** [comment]
already done :-)
