### ISSUE TITLE
JsonHttpClient.ino Failed to configure Ethernet

### ISSUE THREAD

**Issue by kennblvnp** [bblanchon/ArduinoJson#908]
I tried to run this example https://arduinojson.org/v5/example/http-client/

it gives me an error Failed to configure Ethernet

Running on windows 10. Arduino UNO 1.8

**Comment by bblanchon** [comment]
Hi Kenn,

This problem is not related to ArduinoJson.
Please try the WebClient example from the Ethernet library:
![image](https://user-images.githubusercontent.com/5462433/53153285-3458cc00-35b8-11e9-8e43-196d22c652ab.png)

You should also check the documentation for the Ethernet library:
https://www.arduino.cc/en/reference/ethernet

Regards,
Benoit
