### ISSUE TITLE
SerializeJson not working when use softserial 

### ISSUE THREAD

**Issue by Sketh** [bblanchon/ArduinoJson#919]
IDE:1.8.8
Board:Arduino UNO
When i use below code i can get result of print like this.
`{
  "result": [
    {
      "ID": "01",
      "Value": [
        "2",
        "1",
        "13"
      ]
    }
  ]
}`
But when i use SoftwareSerial and in the setup to being that the serializeJson result like this.
`{}`
I don't know what happen in the softserial with using json library, can tell me why?
```
#include <SoftwareSerial.h>
#include <ArduinoJson.h>
int dir[3];
char  json[] ="{\"ID\":\"01\",\"Value\":[\"%d\",\"%d\",\"%d\"]}";
//SoftwareSerial Left(8,9);//左
//SoftwareSerial Right(6,7); //右 
//SoftwareSerial Up(10,11);//上
//SoftwareSerial Down(14,15);//下
//SoftwareSerial Global(8,9);  //建立軟體串列埠腳位 (RX, TX)左
void setup() {
 
  Serial.begin(9600);        //設定硬體串列埠速率
 // Up.begin(9600);
 // Right.begin(9600);
  //Global.begin(9600);   //設定軟體串列埠速率
  }

void loop() {
  
 dir[0]=2;
 dir[1]=1;
 dir[2]=13;
  if(Serial.read()=='j')
{
 StaticJsonDocument<256> docc;
  char b[35];
  sprintf(b, json, dir[0], dir[1],dir[2]);
  deserializeJson(docc, b);
  JsonObject object = docc.as<JsonObject>();
 
  DynamicJsonDocument doc(1024);
 JsonArray result = doc.createNestedArray("result");
  result.add(object);
  result.add(object);
  serializeJsonPretty(doc,Serial);
   }
  }
```

**Comment by bblanchon** [comment]
Hi @Sketh,

The output is empty because the `DynamicJsonDocument` failed to allocate the memory pool.
There is not enough RAM for the two JsonDocuments and the SoftwareSerial library.

Your program works with the `HardwareSerial` because it doesn't require additional RAM.
Your program fails with the `SoftwareSerial` because the library uses some RAM for the buffers.

I added an entry in the FAQ:

* [Why is the output incomplete?](https://arduinojson.org/v6/faq/why-is-the-output-incomplete/?utm_source=github&utm_medium=issues)

Regards,
Benoit
